use aiml;

CREATE VIEW SEM_3 AS
SELECT ROLL_NO, NAME FROM STUDENTS
    WHERE SEMESTER = 3;

SELECT
    *
FROM
    SEM_3;

INSERT INTO SEM_3 VALUES (2214151, "Rajesh");

SELECT
    *
FROM
    SEM_3;

DROP VIEW SEM_3;
DELETE FROM SEM_3 WHERE ROLL_NO = 2214151;
UPDATE SEM_3 SET NAME = "Rajesh" WHERE ROLL_NO = 2214151;




CREATE SYNONYM STD FOR STUDENTS;
DROP SYNONYM STD;
CREATE SEQUENCE ROLLNO INCREMENT BY 1;
ALTER SEQUENCE ROLLNO INCREMENT BY 2;
DROP SEQUENCE ROLLNO;

CREATE INDEX STD_ROLL ON STUDENTS(ROLL_NO);
ALTER INDEX STD_ROLL REBUILD;


SAVEPOINT a;
ROLLBACK TO a